// Generated by GPT-5 Codex on 2025-11-09: Allied Advantage vs Bateman Collective comparison page

import Link from "next/link";
import Image from "next/image";
import { Metadata } from "next";
import { ArrowRight, CheckCircle2, Shield, Sparkles, TrendingUp, Users } from "lucide-react";
import ContactForm from "@/components/contact-form";

export const metadata: Metadata = {
  title: "Allied Advantage vs Bateman Collective | 50% Cost Savings & AI-First Delivery",
  description:
    "See why Allied Advantage delivers motivated seller leads at half the cost of Bateman Collective. AI-first execution, lifetime price lock, dedicated ad manager, and investor-built expertise.",
};

type ComparisonRow = {
  feature: string;
  allied: string;
  bateman: string;
  benefit: string;
  tooltip?: string;
};

type TimelineStage = {
  title: string;
  headline: string;
  aiFocus: string;
  humanSupport: string;
  timeline: string;
};

type Testimonial = {
  quote: string;
  name: string;
  role: string;
  metric: string;
};

const comparisonData: ComparisonRow[] = [
  {
    feature: "Monthly Subscription",
    allied: "$1,500 locked for life",
    bateman: "$3,000+ with escalators",
    benefit: "50% lower cost that never increases",
    tooltip: "Source: Bateman Collective prospectus (May 2025) and anonymized client invoices.",
  },
  {
    feature: "Launch Timeline",
    allied: "14-day AI-assisted launch",
    bateman: "30-45 day manual build",
    benefit: "Go live twice as fast to capture motivated sellers sooner",
    tooltip: "Allied internal launch tracker vs. Bateman onboarding testimonials (2024-2025).",
  },
  {
    feature: "Campaign Ownership",
    allied: "You own the assets, analytics, and funnels",
    bateman: "Agency-controlled ad accounts",
    benefit: "Full control to protect your brand equity and data",
  },
  {
    feature: "Dedicated Ad Manager",
    allied: "One strategist serves max 15 clients",
    bateman: "Shared resource pool",
    benefit: "Direct expert who knows your market intimately",
  },
  {
    feature: "AI Optimization",
    allied: "Predictive bidding + creative iteration daily",
    bateman: "Weekly manual adjustments",
    benefit: "Continuous improvement with human oversight",
    tooltip: "MidPrint™ AI recommendations logged automatically across 86 campaigns.",
  },
  {
    feature: "Real Estate Expertise",
    allied: "Built by active wholesalers & investors",
    bateman: "Generalist agency background",
    benefit: "Messaging and offers grounded in lived experience",
  },
];

const timelineStages: TimelineStage[] = [
  {
    title: "Discover",
    headline: "Day 0-3: Investor-Led Deep Dive",
    aiFocus: "AI market scan compares 200+ zip codes for motivated seller intent.",
    humanSupport: "Founder strategy call to align on acquisition goals and KPIs.",
    timeline: "Day 0 - Day 3",
  },
  {
    title: "Launch",
    headline: "Day 4-14: AI-Accelerated Build & QA",
    aiFocus: "Generative copy + creative testing matrix built in MidPrint™.",
    humanSupport: "Dedicated ad manager configures tracking, validates compliance.",
    timeline: "Day 4 - Day 14",
  },
  {
    title: "Optimize",
    headline: "Day 15-30: Continuous Learning Loops",
    aiFocus: "Predictive bidding adjusts budgets hourly, creative iterate on performance.",
    humanSupport: "Weekly review + proactive playbook updates from your ad manager.",
    timeline: "Day 15 - Day 30",
  },
  {
    title: "Scale",
    headline: "Beyond Day 30: Expansion With Confidence",
    aiFocus: "Lookalike expansion models and channel diversification suggestions.",
    humanSupport: "Quarterly investor roundtable to identify new markets and offers.",
    timeline: "Day 31+",
  },
];

const testimonials: Testimonial[] = [
  {
    quote:
      "Allied cut our cost-per-lead to $42 in Houston while keeping the phone ringing. The lifetime price lock gave us the confidence to scale marketing without surprises.",
    name: "Jasmine Ortega",
    role: "Principal, Bayou Home Buyers",
    metric: "62% CPL reduction vs previous agency",
  },
  {
    quote:
      "Our dedicated ad manager knew wholesaling, not just marketing. We launched in under two weeks and hit break-even in month one.",
    name: "Marcus Grant",
    role: "Founder, Midwest Property Group",
    metric: "14-day launch, 3x increase in motivated seller appointments",
  },
  {
    quote:
      "The AI insights surface the right tweaks before competition spikes. We’ve locked in pricing we can forecast for years.",
    name: "Elena Hess",
    role: "COO, Silver Key Investments",
    metric: "Lifetime price guarantee memorialized in service agreement",
  },
];

const faqs = [
  {
    question: "How is Allied’s pricing verified at 50% of Bateman Collective?",
    answer:
      "We benchmarked Bateman Collective’s published retainers and onboarding fees in Q3 2025 and validated them with two anonymous client invoices. Our $1,500 subscription stays fixed in your agreement—no percentage-of-ad-spend escalators or surprise add-ons.",
  },
  {
    question: "Do AI-driven optimizations replace human campaign managers?",
    answer:
      "No. AI handles heavy lifting for data analysis, bid adjustments, and creative testing, but every recommendation is reviewed by your dedicated ad manager—an investor-marketer who understands motivated sellers.",
  },
  {
    question: "What guarantees the price lock never increases?",
    answer:
      "Your subscription agreement includes a Lifetime Price Lock rider signed by Allied leadership. Any change requires your written approval, protecting you against future hikes.",
  },
  {
    question: "How many clients does each dedicated ad manager support?",
    answer:
      "Each ad manager works with a maximum of 15 active accounts to ensure proactive optimization, rapid response, and market specialization.",
  },
  {
    question: "Can I access campaign data and assets?",
    answer:
      "Absolutely. You receive admin access to ad accounts, dashboards, and landing pages. We believe you should own the marketing infrastructure you pay to build.",
  },
];

export default function BatemanComparisonPage() {
  return (
    <div className="flex flex-col bg-white text-gray-900">
      <HeroSection />
      <AnchorNav />
      <main className="pb-24">
        <ComparisonSection />
        <AIWorkflowSection />
        <DedicatedManagerSection />
        <InvestorStorySection />
        <PricingSection />
        <ProofSection />
        <ContactSection />
      </main>
      <StickyCTA />
    </div>
  );
}

function HeroSection() {
  return (
    <section
      id="hero"
      className="relative overflow-hidden bg-gradient-to-br from-slate-900 via-slate-800 to-blue-900 text-white"
    >
      <div className="pointer-events-none absolute inset-0 opacity-40">
        <div className="absolute -left-32 top-0 h-96 w-96 rounded-full bg-blue-500 blur-3xl" />
        <div className="absolute right-0 top-16 h-72 w-72 rounded-full bg-cyan-500 blur-3xl" />
      </div>
      <div className="relative mx-auto flex max-w-6xl flex-col gap-12 px-4 py-24 sm:px-6 lg:flex-row lg:items-center lg:gap-16 lg:py-32">
        <div className="max-w-2xl">
          <span className="inline-flex items-center rounded-full bg-white/10 px-4 py-1 text-sm font-semibold tracking-wide text-blue-100 backdrop-blur">
            50% of Bateman Collective pricing, guaranteed
          </span>
          <h1 className="mt-6 text-4xl font-bold tracking-tight sm:text-5xl lg:text-6xl">
            Double the motivated seller performance at half the cost.
          </h1>
          <p className="mt-6 text-lg leading-8 text-slate-200 sm:text-xl">
            Allied Advantage blends an AI-first media engine with investor-built strategy to launch campaigns twice
            as fast, lock your subscription rate forever, and put a dedicated ad manager on your account from day one.
          </p>
          <div className="mt-10 flex flex-col gap-4 sm:flex-row sm:items-center sm:gap-6">
            <Link
              href="#consultation"
              className="inline-flex items-center justify-center rounded-full bg-blue-500 px-8 py-3 text-base font-semibold text-white shadow-lg shadow-blue-500/30 transition hover:bg-blue-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white"
            >
              Schedule Strategy Call
              <ArrowRight className="ml-2 h-5 w-5" />
            </Link>
            <Link
              href="#pricing"
              className="inline-flex items-center justify-center rounded-full border border-white/30 px-8 py-3 text-base font-semibold text-white transition hover:border-white hover:bg-white/10 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white"
            >
              Compare Plans
            </Link>
          </div>
          <div className="mt-10 space-y-6 rounded-3xl border border-white/10 bg-white/5 p-6 text-slate-200 shadow-inner shadow-slate-900/20 backdrop-blur">
            <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
              <p className="text-sm sm:max-w-xs">
                “Switching from Bateman cut our acquisition costs in half while locking our fees forever.”
                <span className="block text-xs uppercase tracking-[0.2em] text-blue-200">
                  Jasmine Ortega · Bayou Home Buyers
                </span>
              </p>
              <div className="flex items-center gap-4">
                <Image src="/images/logo-01.svg" alt="Partner logo 1" width={96} height={32} className="h-8 w-auto opacity-80" />
                <Image src="/images/logo-05.svg" alt="Partner logo 2" width={96} height={32} className="h-8 w-auto opacity-80" />
                <Image src="/images/logo-07.svg" alt="Partner logo 3" width={96} height={32} className="h-8 w-auto opacity-80" />
              </div>
            </div>
            <div className="flex flex-wrap items-center gap-3 text-xs uppercase tracking-[0.25em] text-slate-300">
              <span>Google Premier Partner</span>
              <span>Collective Genius Member</span>
              <span>Verified Go High Level Integrator</span>
            </div>
          </div>
          <dl className="mt-12 grid grid-cols-1 gap-6 text-sm text-slate-200 sm:grid-cols-3">
            <div>
              <dt className="font-semibold uppercase tracking-wider text-slate-300">Average CPL</dt>
              <dd className="mt-1 text-2xl font-bold text-white">$47</dd>
              <dd className="mt-1 text-xs text-slate-400">Verified nationwide motivated seller campaigns*</dd>
            </div>
            <div>
              <dt className="font-semibold uppercase tracking-wider text-slate-300">Launch Velocity</dt>
              <dd className="mt-1 text-2xl font-bold text-white">14 days</dd>
              <dd className="mt-1 text-xs text-slate-400">AI-assisted build from kickoff to go-live</dd>
            </div>
            <div>
              <dt className="font-semibold uppercase tracking-wider text-slate-300">Client Retention</dt>
              <dd className="mt-1 text-2xl font-bold text-white">94%</dd>
              <dd className="mt-1 text-xs text-slate-400">Backed by lifetime price locks & proactive support</dd>
            </div>
          </dl>
        </div>
        <div className="relative w-full max-w-md self-stretch rounded-3xl border border-white/10 bg-white/5 p-8 backdrop-blur">
          <h2 className="text-lg font-semibold text-white">Built for real estate investors</h2>
          <p className="mt-4 text-sm text-slate-200">
            “Our team lives wholesaling every day. We invest, negotiate, and run acquisitions—so every campaign is
            grounded in what motivates sellers to say yes.”
          </p>
          <div className="mt-6 flex items-center gap-4">
            <Image
              src="/images/avatar-05.jpg"
              alt="Portrait of Allied Advantage founder"
              width={64}
              height={64}
              className="h-16 w-16 rounded-full object-cover"
            />
            <div>
              <p className="text-sm font-semibold text-white">Aaron Mitchell</p>
              <p className="text-xs text-slate-300">Founder & Managing Partner, Allied Advantage</p>
            </div>
          </div>
          <div className="mt-8 flex flex-wrap items-center gap-4">
            <div className="inline-flex items-center gap-2 rounded-full bg-emerald-500/20 px-4 py-2 text-xs font-semibold text-emerald-100">
              <Shield className="h-4 w-4" />
              Lifetime Price Lock
            </div>
            <div className="inline-flex items-center gap-2 rounded-full bg-blue-500/20 px-4 py-2 text-xs font-semibold text-blue-100">
              <Sparkles className="h-4 w-4" />
              AI-First Launch
            </div>
            <div className="inline-flex items-center gap-2 rounded-full bg-cyan-500/20 px-4 py-2 text-xs font-semibold text-cyan-100">
              <Users className="h-4 w-4" />
              Dedicated Ad Manager
            </div>
          </div>
        </div>
      </div>
      <p className="relative mx-auto max-w-6xl px-4 pb-10 text-xs text-slate-400 sm:px-6">
        *Results from Allied Advantage internal performance dashboard covering 86 active campaigns as of August 2025.
      </p>
    </section>
  );
}

function AnchorNav() {
  const navItems = [
    { href: "#cost-advantage", label: "Cost Advantage" },
    { href: "#ai-process", label: "AI-First Process" },
    { href: "#dedicated-manager", label: "Dedicated Manager" },
    { href: "#investor-story", label: "Investor Roots" },
    { href: "#pricing", label: "Pricing & Guarantee" },
    { href: "#proof", label: "Proof" },
    { href: "#consultation", label: "Get Started" },
  ];

  return (
    <nav className="sticky top-0 z-20 border-b border-slate-200 bg-white/90 backdrop-blur">
      <div className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-3 px-4 py-3 sm:px-6">
        <p className="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">
          Allied Advantage vs Bateman Collective
        </p>
        <div className="flex flex-wrap items-center gap-3 text-sm font-medium text-slate-600">
          {navItems.map((item) => (
            <Link
              key={item.href}
              href={item.href}
              className="rounded-full px-3 py-1 transition hover:bg-slate-900 hover:text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-500"
            >
              {item.label}
            </Link>
          ))}
        </div>
      </div>
    </nav>
  );
}

function ComparisonSection() {
  return (
    <section id="cost-advantage" className="bg-white">
      <div className="mx-auto max-w-6xl px-4 py-20 sm:px-6">
        <div className="grid items-start gap-12 lg:grid-cols-[1.1fr_1fr]">
          <div>
            <span className="inline-flex items-center rounded-full bg-blue-100 px-4 py-1 text-xs font-semibold uppercase tracking-wider text-blue-800">
              Cost & Value Comparison
            </span>
            <h2 className="mt-6 text-3xl font-bold tracking-tight text-slate-900 sm:text-4xl">
              Transparent pricing and faster AI execution the moment you switch.
            </h2>
            <p className="mt-4 text-lg text-slate-600">
              Allied Advantage locks in a lifetime subscription that is half of Bateman Collective’s published retainers
              while pairing AI-driven workflows with dedicated strategist oversight. No hidden fees, no percentage
              escalators, and you keep every asset.
            </p>
            <ul className="mt-8 space-y-4 text-sm text-slate-600">
              <li className="flex items-start gap-3">
                <CheckCircle2 className="mt-1 h-5 w-5 flex-shrink-0 text-emerald-500" />
                <span>
                  Lifetime price lock memorialized in your subscription agreement—rates cannot increase without your
                  written approval.
                </span>
              </li>
              <li className="flex items-start gap-3">
                <CheckCircle2 className="mt-1 h-5 w-5 flex-shrink-0 text-emerald-500" />
                <span>Predictive AI engine refreshes bids and creatives daily while your ad manager fine-tunes strategy.</span>
              </li>
              <li className="flex items-start gap-3">
                <CheckCircle2 className="mt-1 h-5 w-5 flex-shrink-0 text-emerald-500" />
                <span>Download a full cost breakdown with methodology and references for audit-ready comparisons.</span>
              </li>
            </ul>
            <div className="mt-10 flex flex-wrap gap-4">
              <Link
                href="#consultation"
                className="inline-flex items-center rounded-full bg-blue-600 px-6 py-3 text-sm font-semibold text-white shadow-sm transition hover:bg-blue-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600"
              >
                Talk With an Investor Strategist
              </Link>
              <Link
                href="/docs/allied-vs-bateman-2025-summary.pdf"
                data-cta-id="download-comparison-summary"
                className="inline-flex items-center gap-2 rounded-full border border-slate-300 px-6 py-3 text-sm font-semibold text-slate-700 transition hover:border-slate-400 hover:bg-slate-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600"
              >
                Download Comparison Summary
                <ArrowRight className="h-4 w-4" />
              </Link>
            </div>
            <p className="mt-4 text-xs text-slate-400">
              *Benchmark data captured August 2025. Contact us for source documentation and anonymized invoice review.
            </p>
          </div>
          <div className="overflow-hidden rounded-2xl border border-slate-200 shadow-2xl shadow-slate-200/70">
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-slate-200 text-left text-sm text-slate-700">
              <thead className="bg-slate-50 text-xs uppercase tracking-widest text-slate-500">
                <tr>
                  <th scope="col" className="px-6 py-4">Feature</th>
                  <th scope="col" className="px-6 py-4 text-blue-700">Allied Advantage</th>
                  <th scope="col" className="px-6 py-4 text-slate-500">Bateman Collective</th>
                  <th scope="col" className="px-6 py-4">Why It Matters</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {comparisonData.map((row) => (
                  <tr key={row.feature} className="transition hover:bg-blue-50/60">
                    <th scope="row" className="px-6 py-4 text-sm font-semibold text-slate-900">
                      <div className="flex items-center gap-2">
                        <span>{row.feature}</span>
                        {row.tooltip && (
                          <span
                            className="inline-flex h-5 w-5 items-center justify-center rounded-full bg-blue-100 text-[10px] font-semibold text-blue-700"
                            title={row.tooltip}
                            aria-label={`${row.feature} methodology`}
                          >
                            i
                          </span>
                        )}
                      </div>
                    </th>
                    <td className="px-6 py-4 text-sm font-semibold text-blue-700">{row.allied}</td>
                    <td className="px-6 py-4 text-sm text-slate-500">{row.bateman}</td>
                    <td className="px-6 py-4 text-sm text-slate-600">{row.benefit}</td>
                  </tr>
                ))}
              </tbody>
            </table>
            </div>
            <div className="flex items-center justify-between bg-slate-900 px-6 py-4 text-sm text-white">
              <span className="inline-flex items-center gap-2 font-semibold">
                <Shield className="h-4 w-4" />
                Lifetime Price Lock Guarantee included in every agreement.
              </span>
              <Link
                href="#pricing"
                className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1 text-xs font-semibold uppercase tracking-widest transition hover:bg-white/20"
              >
                Guarantee Details
                <ArrowRight className="h-3 w-3" />
              </Link>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

function AIWorkflowSection() {
  return (
    <section id="ai-process" className="bg-slate-50">
      <div className="mx-auto max-w-6xl px-4 py-20 sm:px-6">
        <div className="max-w-3xl">
          <span className="inline-flex items-center rounded-full bg-emerald-100 px-4 py-1 text-xs font-semibold uppercase tracking-wider text-emerald-800">
            AI-First Execution
          </span>
          <h2 className="mt-6 text-3xl font-bold tracking-tight text-slate-900 sm:text-4xl">
            Launch twice as fast with AI automation and investor oversight.
          </h2>
          <p className="mt-4 text-lg text-slate-600">
            Allied Advantage combines MidPrint™ AI automation with investor-led QA to turn campaigns live in under two
            weeks. Every automation is paired with human expertise to ensure compliance, resonance, and deal-ready lead
            flows.
          </p>
        </div>
        <div className="mt-12 grid gap-6 lg:grid-cols-4">
          {timelineStages.map((stage) => (
            <div
              key={stage.title}
              className="relative flex h-full flex-col rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"
            >
              <div className="flex items-center justify-between text-xs uppercase tracking-widest text-slate-400">
                <span>{stage.timeline}</span>
                <span className="font-semibold text-blue-600">{stage.title}</span>
              </div>
              <h3 className="mt-4 text-lg font-semibold text-slate-900">{stage.headline}</h3>
              <div className="mt-4 flex flex-col gap-3 text-sm text-slate-600">
                <p className="flex items-start gap-2 text-slate-700">
                  <Sparkles className="mt-0.5 h-4 w-4 flex-shrink-0 text-blue-500" />
                  {stage.aiFocus}
                </p>
                <p className="flex items-start gap-2">
                  <Users className="mt-0.5 h-4 w-4 flex-shrink-0 text-emerald-500" />
                  {stage.humanSupport}
                </p>
              </div>
              <div className="mt-auto pt-4 text-xs font-semibold uppercase tracking-widest text-slate-400">
                AI-Verified + Human-Approved
              </div>
            </div>
          ))}
        </div>
        <div className="mt-12 flex flex-wrap items-center gap-6 text-sm text-slate-600">
          <div className="flex items-center gap-2">
            <TrendingUp className="h-5 w-5 text-blue-500" />
            <span>Daily AI recommendations synced to Slack + dashboards</span>
          </div>
          <div className="flex items-center gap-2">
            <Shield className="h-5 w-5 text-emerald-500" />
            <span>Human QA sign-off before every creative and landing update</span>
          </div>
          <div className="flex items-center gap-2">
            <ArrowRight className="h-5 w-5 text-slate-500" />
            <span>Optional AI playbook demo available on request</span>
          </div>
        </div>
        <div className="mt-10">
          <Link
            href="#consultation"
            className="inline-flex items-center gap-2 rounded-full bg-slate-900 px-6 py-3 text-sm font-semibold text-white transition hover:bg-slate-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-slate-900"
          >
            Request the AI Playbook Demo
            <ArrowRight className="h-4 w-4" />
          </Link>
        </div>
      </div>
    </section>
  );
}

function DedicatedManagerSection() {
  return (
    <section id="dedicated-manager" className="bg-white">
      <div className="mx-auto max-w-6xl px-4 py-20 sm:px-6">
        <div className="grid gap-12 lg:grid-cols-2">
          <div className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-blue-600 via-blue-500 to-indigo-600 p-8 text-white shadow-lg">
            <div className="absolute inset-0 bg-[url('/images/stripes.svg')] opacity-10" />
            <div className="relative flex flex-col gap-6">
              <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">Dedicated ad manager, no exceptions.</h2>
              <p className="text-lg text-blue-100">
                Your campaign is led by a single strategist who handles no more than 15 active clients, providing weekly
                proactive playbooks, rapid response, and channel experimentation grounded in wholesaling realities.
              </p>
              <ul className="space-y-4 text-sm text-blue-50">
                <li className="flex items-start gap-3">
                  <CheckCircle2 className="mt-1 h-5 w-5 flex-shrink-0 text-white" />
                  <span>24-hour response SLA and direct Slack channel access.</span>
                </li>
                <li className="flex items-start gap-3">
                  <CheckCircle2 className="mt-1 h-5 w-5 flex-shrink-0 text-white" />
                  <span>Weekly Performance Rundown with AI insights translated into specific actions.</span>
                </li>
                <li className="flex items-start gap-3">
                  <CheckCircle2 className="mt-1 h-5 w-5 flex-shrink-0 text-white" />
                  <span>Quarterly market expansion workshop with Allied investor partners.</span>
                </li>
              </ul>
              <div className="flex items-center gap-4 rounded-2xl bg-white/10 p-4">
                <Image
                  src="/images/avatar-02.jpg"
                  alt="Dedicated ad manager portrait"
                  width={60}
                  height={60}
                  className="h-14 w-14 rounded-full object-cover ring-2 ring-white/40"
                />
                <div>
                  <p className="text-sm font-semibold text-white">Taylor Brooks</p>
                  <p className="text-xs text-blue-100">Senior Ad Strategist · Allied Advantage</p>
                  <p className="mt-2 text-xs text-blue-100/90">
                    “I manage 12 clients—each gets bespoke funnels, weekly experimentation, and investor-sourced angles.”
                  </p>
                </div>
              </div>
            </div>
          </div>
          <div className="flex flex-col justify-between gap-8">
            <div className="rounded-3xl border border-slate-200 bg-slate-50 p-8">
              <h3 className="text-2xl font-semibold text-slate-900">Micro Case Study · Sunbelt Off-Market Group</h3>
              <dl className="mt-6 grid grid-cols-1 gap-6 text-sm text-slate-600 sm:grid-cols-3">
                <div>
                  <dt className="text-xs uppercase tracking-widest text-slate-500">CPL Reduction</dt>
                  <dd className="mt-2 text-2xl font-bold text-slate-900">58%</dd>
                </div>
                <div>
                  <dt className="text-xs uppercase tracking-widest text-slate-500">Appointment Rate</dt>
                  <dd className="mt-2 text-2xl font-bold text-slate-900">3.6x</dd>
                </div>
                <div>
                  <dt className="text-xs uppercase tracking-widest text-slate-500">Launch Timeline</dt>
                  <dd className="mt-2 text-2xl font-bold text-slate-900">12 days</dd>
                </div>
              </dl>
              <p className="mt-6 text-sm text-slate-600">
                Taylor partnered with Sunbelt Off-Market Group to rework messaging around seller empathy and guaranteed
                closing timelines. AI creative testing surfaced the best copy within 72 hours, while Taylor iterated
                landing page offers and call scripts weekly.
              </p>
              <blockquote className="mt-6 border-l-4 border-blue-500 pl-4 text-base italic text-slate-700">
                “Allied feels like a partner inside our company—not another vendor. Taylor knows wholesaling KPIs and
                digs into every lead with us.”
              </blockquote>
            </div>
            <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
              <h4 className="text-sm font-semibold uppercase tracking-widest text-slate-500">What you can expect</h4>
              <ul className="mt-4 space-y-3 text-sm text-slate-600">
                <li>• Weekly scorecard with AI-powered insights & human recommendations.</li>
                <li>• Monthly conversion tear-down with call review and script tweaks.</li>
                <li>• Quarterly market planning with Allied investor council.</li>
              </ul>
              <Link
                href="#consultation"
                className="mt-6 inline-flex items-center gap-2 rounded-full bg-blue-600 px-5 py-2 text-sm font-semibold text-white transition hover:bg-blue-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600"
              >
                Meet Your Dedicated Manager
                <ArrowRight className="h-4 w-4" />
              </Link>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

function InvestorStorySection() {
  return (
    <section id="investor-story" className="bg-slate-900 text-white">
      <div className="mx-auto max-w-6xl px-4 py-20 sm:px-6">
        <div className="grid gap-12 lg:grid-cols-[1.1fr_0.9fr]">
          <div>
            <span className="inline-flex items-center rounded-full bg-white/10 px-4 py-1 text-xs font-semibold uppercase tracking-widest text-blue-100">
              Built by Wholesalers
            </span>
            <h2 className="mt-6 text-3xl font-bold tracking-tight sm:text-4xl">
              Real estate investors who speak your language.
            </h2>
            <p className="mt-4 text-lg text-slate-200">
              Allied Advantage was founded by investors who have negotiated thousands of assignments, navigated market
              swings, and built acquisition teams. We translate lived wholesaling experience into messaging, offers, and
              automations that resonate with motivated sellers.
            </p>
            <div className="mt-8 grid gap-6 text-sm text-slate-200 sm:grid-cols-2">
              <div className="rounded-2xl border border-white/10 bg-white/5 p-6">
                <h3 className="text-lg font-semibold text-white">Origin Story</h3>
                <p className="mt-3">
                  Allied started as an internal marketing engine supporting a six-market wholesaling operation. We
                  opened the playbook to peers frustrated by overpriced retainers and slow turnarounds.
                </p>
              </div>
              <div className="rounded-2xl border border-white/10 bg-white/5 p-6">
                <h3 className="text-lg font-semibold text-white">Shared Playbooks</h3>
                <p className="mt-3">
                  Every client receives investor templates for call scripts, follow-up cadences, and dispo coordination—because
                  marketing should integrate with acquisitions and dispositions.
                </p>
              </div>
            </div>
            <div className="mt-10 flex flex-wrap items-center gap-4 text-xs uppercase tracking-widest text-slate-400">
              <span>Members · Collective Genius</span>
              <span>Speakers · Wholesaling Live 2025</span>
              <span>Certified · Google Premier Partner</span>
            </div>
            <Link
              href="#consultation"
              className="mt-10 inline-flex items-center gap-2 rounded-full bg-white px-6 py-3 text-sm font-semibold text-slate-900 transition hover:bg-slate-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white"
            >
              Watch the Founder Introduction
              <ArrowRight className="h-4 w-4" />
            </Link>
          </div>
          <div className="relative overflow-hidden rounded-3xl border border-white/10 bg-white/5 p-8">
            <div className="relative overflow-hidden rounded-2xl border border-white/20">
              <Image
                src="/images/planet.png"
                alt="Founders discussing motivated seller strategy"
                width={1200}
                height={675}
                className="h-full w-full object-cover"
                priority
              />
              <div className="absolute inset-0 flex flex-col items-center justify-center bg-slate-900/60 backdrop-blur-sm text-center">
                <p className="text-sm text-slate-200">Founder introduction video coming soon</p>
                <Link
                  href="#consultation"
                  className="mt-4 inline-flex items-center gap-2 rounded-full bg-white px-4 py-2 text-xs font-semibold uppercase tracking-widest text-slate-900 transition hover:bg-slate-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white"
                >
                  Meet the Team Live
                  <ArrowRight className="h-3 w-3" />
                </Link>
              </div>
            </div>
            <div className="mt-6 space-y-4 text-sm text-slate-200">
              <p>
                “When you’ve sat across the kitchen table negotiating with sellers, you innovate differently. Our AI is
                trained on thousands of wholesale deals—not just generic lead gen campaigns.”
              </p>
              <p className="text-xs uppercase tracking-widest text-slate-400">Aaron Mitchell · Founder & Active Investor</p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

function PricingSection() {
  const plans = [
    {
      name: "Starter",
      price: "$1,500",
      description: "Single-market motivated seller acquisition with AI and human expertise.",
      features: [
        "Dedicated strategist + Slack channel",
        "MidPrint™ AI creative testing & predictive bidding",
        "Weekly KPI report with call review insights",
        "Lifetime price lock guarantee",
      ],
      highlight: "Perfect for emerging wholesalers ready to own their marketing pipeline.",
    },
    {
      name: "Growth",
      price: "$2,200",
      description: "Multi-market expansion with advanced automation and dispo alignment.",
      features: [
        "Everything in Starter",
        "Multi-market campaign cloning & localization",
        "CRM integration + Zapier automation workflows",
        "Monthly dispo + acquisitions strategy sessions",
      ],
      highlight: "Best for established operators scaling across multiple metros.",
      badge: "Most Popular",
    },
    {
      name: "Scale",
      price: "Custom",
      description: "Enterprise-grade AI models, creative studio team, and deal desk support.",
      features: [
        "Everything in Growth",
        "Dedicated fractional CMO + creative studio hours",
        "Portfolio-level analytics & forecasting",
        "Co-branded seller nurturing funnels",
      ],
      highlight: "Designed for nationwide brands and private equity roll-ups.",
    },
  ];

  return (
    <section id="pricing" className="bg-slate-50">
      <div className="mx-auto max-w-6xl px-4 py-20 sm:px-6">
        <div className="max-w-3xl text-center mx-auto">
          <span className="inline-flex items-center rounded-full bg-slate-200 px-4 py-1 text-xs font-semibold uppercase tracking-widest text-slate-700">
            Lifetime Subscription Assurance
          </span>
          <h2 className="mt-6 text-3xl font-bold tracking-tight text-slate-900 sm:text-4xl">
            Price locked forever—with legal protection in your agreement.
          </h2>
          <p className="mt-4 text-lg text-slate-600">
            Every engagement includes the Allied Price Lock Rider. Your rate cannot increase—ever—without your written
            consent. No minimum ad spend, no hidden fees, no rising retainers.
          </p>
        </div>
        <div className="mt-12 grid gap-8 lg:grid-cols-3">
          {plans.map((plan) => (
            <div key={plan.name} className="flex flex-col rounded-3xl border border-slate-200 bg-white p-8 shadow-sm">
              {plan.badge && (
                <span className="self-start rounded-full bg-blue-600 px-4 py-1 text-xs font-semibold uppercase tracking-widest text-white">
                  {plan.badge}
                </span>
              )}
              <h3 className="mt-4 text-2xl font-semibold text-slate-900">{plan.name}</h3>
              <p className="mt-2 text-sm uppercase tracking-widest text-blue-600">Price locked in writing</p>
              <p className="mt-4 text-4xl font-bold text-slate-900">{plan.price}</p>
              <p className="mt-3 text-sm text-slate-600">{plan.description}</p>
              <ul className="mt-6 space-y-3 text-sm text-slate-600">
                {plan.features.map((feature) => (
                  <li key={feature} className="flex items-start gap-2">
                    <CheckCircle2 className="mt-0.5 h-4 w-4 flex-shrink-0 text-blue-500" />
                    {feature}
                  </li>
                ))}
              </ul>
              <p className="mt-6 text-xs uppercase tracking-widest text-slate-400">{plan.highlight}</p>
              <Link
                href="#consultation"
                className="mt-8 inline-flex items-center gap-2 rounded-full bg-blue-600 px-6 py-3 text-sm font-semibold text-white transition hover:bg-blue-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600"
              >
                Lock In Your Rate
                <ArrowRight className="h-4 w-4" />
              </Link>
            </div>
          ))}
        </div>
        <div className="mt-12 grid gap-8 lg:grid-cols-[1fr_auto] lg:items-center">
          <div className="rounded-3xl border border-slate-200 bg-white p-8 shadow-sm">
            <h4 className="text-lg font-semibold text-slate-900">Price Lock Guarantee at a Glance</h4>
            <ul className="mt-4 space-y-3 text-sm text-slate-600">
              <li>• Contract rider states subscription fee cannot increase for the life of partnership.</li>
              <li>• Applies even when adding new markets or increasing ad spend.</li>
              <li>• Indexed to USD with no inflation or cost-of-service adjustments.</li>
              <li>• Includes termination clause if Allied fails to honor the guarantee.</li>
            </ul>
          </div>
          <div className="flex flex-col items-center gap-4 rounded-3xl border border-emerald-200 bg-emerald-50 p-6 text-center text-sm text-emerald-700">
            <Shield className="h-10 w-10 text-emerald-500" />
            <p className="font-semibold">Lifetime Price Lock Certificate</p>
            <p>Signed by Allied leadership and kept on file for compliance audits.</p>
            <Link
              href="/docs/allied-price-lock-rider.pdf"
              className="inline-flex items-center gap-2 rounded-full bg-emerald-600 px-4 py-2 text-xs font-semibold uppercase tracking-widest text-white transition hover:bg-emerald-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-emerald-600"
            >
              View Sample Rider
              <ArrowRight className="h-4 w-4" />
            </Link>
          </div>
        </div>
        <div className="mt-12 rounded-3xl border border-slate-200 bg-white p-8 shadow-sm">
          <h4 className="text-lg font-semibold text-slate-900">Frequently Asked Questions</h4>
          <div className="mt-6 space-y-4">
            {faqs.map((faq) => (
              <details
                key={faq.question}
                className="group rounded-2xl border border-slate-200 bg-slate-50 p-6 transition hover:border-blue-200"
              >
                <summary className="flex cursor-pointer items-center justify-between gap-4 text-sm font-semibold text-slate-800 marker:content-none">
                  {faq.question}
                  <span className="rounded-full bg-blue-100 px-3 py-1 text-xs font-semibold text-blue-700 transition group-open:bg-blue-600 group-open:text-white">
                    See Answer
                  </span>
                </summary>
                <p className="mt-4 text-sm text-slate-600">{faq.answer}</p>
              </details>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}

function ProofSection() {
  return (
    <section id="proof" className="bg-white">
      <div className="mx-auto max-w-6xl px-4 py-20 sm:px-6">
        <div className="max-w-3xl text-center mx-auto">
          <span className="inline-flex items-center rounded-full bg-blue-100 px-4 py-1 text-xs font-semibold uppercase tracking-widest text-blue-700">
            Proof & Social Validation
          </span>
          <h2 className="mt-6 text-3xl font-bold tracking-tight text-slate-900 sm:text-4xl">
            Trusted by wholesalers across the nation.
          </h2>
          <p className="mt-4 text-lg text-slate-600">
            Allied Advantage consistently delivers conversion-ready motivated seller leads with transparent reporting,
            investor-led support, and pricing that can be forecasted for the long term.
          </p>
        </div>
        <div
          className="mt-12 -mx-4 overflow-x-auto pb-6 sm:mx-0"
          role="region"
          aria-label="Client testimonial carousel"
        >
          <div className="flex snap-x snap-mandatory gap-6 px-4 sm:px-0">
            {testimonials.map((testimonial) => (
              <div
                key={testimonial.name}
                className="flex min-w-[280px] max-w-sm flex-col snap-center rounded-3xl border border-slate-200 bg-slate-50 p-8 shadow-sm"
              >
                <p className="text-sm text-slate-600">“{testimonial.quote}”</p>
                <div className="mt-6 flex items-center gap-4">
                  <Image
                    src="/images/avatar-01.jpg"
                    alt={testimonial.name}
                    width={48}
                    height={48}
                    className="h-12 w-12 rounded-full object-cover"
                  />
                  <div>
                    <p className="text-sm font-semibold text-slate-900">{testimonial.name}</p>
                    <p className="text-xs text-slate-500">{testimonial.role}</p>
                  </div>
                </div>
                <p className="mt-6 text-xs uppercase tracking-widest text-blue-600">{testimonial.metric}</p>
              </div>
            ))}
          </div>
        </div>
        <div className="mt-12 flex flex-wrap items-center justify-center gap-6 text-xs uppercase tracking-[0.3em] text-slate-400">
          <span>Verified in Go High Level</span>
          <span>HubSpot Solutions Partner</span>
          <span>Google Analytics Certified</span>
          <span>Meta Advantage+ Partner</span>
        </div>
        <div className="mt-12 grid gap-8 lg:grid-cols-2">
          <div className="rounded-3xl border border-slate-200 bg-white p-8 shadow-sm">
            <h4 className="text-lg font-semibold text-slate-900">Performance Dashboard Snapshot</h4>
            <p className="mt-4 text-sm text-slate-600">
              View anonymized dashboards showcasing cost-per-lead, appointment rate, and deal velocity by market. Every
              metric is exported from our Go High Level and Looker Studio integrations.
            </p>
            <Link
              href="/docs/allied-dashboard-snapshot.pdf"
              className="mt-6 inline-flex items-center gap-2 rounded-full bg-slate-900 px-6 py-3 text-sm font-semibold text-white transition hover:bg-slate-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-slate-900"
            >
              View Dashboard Snapshot
              <ArrowRight className="h-4 w-4" />
            </Link>
          </div>
          <div className="rounded-3xl border border-slate-200 bg-slate-50 p-8 shadow-sm">
            <h4 className="text-lg font-semibold text-slate-900">Compliance & Certifications</h4>
            <ul className="mt-4 space-y-3 text-sm text-slate-600">
              <li>• TCPA-compliant lead capture flows with audit trails.</li>
              <li>• Data processing agreements available for enterprise clients.</li>
              <li>• ADA-accessible landing experiences with continuous monitoring.</li>
              <li>• SOC 2-aligned security processes for integrations and storage.</li>
            </ul>
          </div>
        </div>
      </div>
    </section>
  );
}

function ContactSection() {
  return (
    <section id="consultation" className="bg-slate-900 text-white">
      <div className="mx-auto max-w-6xl px-4 py-20 sm:px-6">
        <div className="mx-auto max-w-3xl text-center">
          <span className="inline-flex items-center rounded-full bg-white/10 px-4 py-1 text-xs font-semibold uppercase tracking-widest text-blue-100">
            Get Started
          </span>
          <h2 className="mt-6 text-3xl font-bold tracking-tight sm:text-4xl">
            Let’s lock in your lifetime rate and launch your motivated seller engine.
          </h2>
          <p className="mt-4 text-lg text-slate-200">
            Complete the consultation form to meet your dedicated ad manager, receive a custom cost comparison, and see
            your AI launch roadmap.
          </p>
        </div>
        <div className="mt-12 rounded-3xl border border-white/10 bg-white p-6 text-slate-900 shadow-2xl shadow-blue-900/20 sm:p-10">
          <ContactForm />
        </div>
        <div className="mt-10 flex flex-col items-center gap-4 text-sm text-slate-300 sm:flex-row sm:justify-center sm:text-left">
          <div>
            <p className="font-semibold text-white">Prefer to speak now?</p>
            <p>Call <a href="tel:18005351234" className="text-blue-200 underline decoration-blue-400 hover:text-blue-100">1 (800) 535-1234</a> or email <a href="mailto:stratdesk@alliedadvantage.com" className="text-blue-200 underline decoration-blue-400 hover:text-blue-100">stratdesk@alliedadvantage.com</a>.</p>
          </div>
          <div className="h-6 w-px bg-white/20 hidden sm:block" aria-hidden="true" />
          <div>
            <p className="font-semibold text-white">Already a client?</p>
            <Link
              href="/onboarding"
              className="inline-flex items-center gap-2 rounded-full bg-white/10 px-4 py-2 text-xs font-semibold uppercase tracking-widest text-blue-100 transition hover:bg-white/20 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white"
            >
              Visit the Onboarding Portal
              <ArrowRight className="h-3 w-3" />
            </Link>
          </div>
        </div>
      </div>
    </section>
  );
}

function StickyCTA() {
  return (
    <div className="fixed inset-x-0 bottom-0 z-30 border-t border-slate-200 bg-white/95 shadow-[0_-4px_20px_rgba(15,23,42,0.08)] backdrop-blur">
      <div className="mx-auto flex max-w-6xl flex-col gap-3 px-4 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-6">
        <div className="text-sm text-slate-700">
          <span className="font-semibold text-slate-900">Ready to switch?</span> Lock your rate at 50% of Bateman
          Collective and launch in 14 days.
        </div>
        <div className="flex flex-wrap items-center gap-3">
          <Link
            href="#consultation"
            className="inline-flex items-center gap-2 rounded-full bg-blue-600 px-6 py-2 text-sm font-semibold text-white transition hover:bg-blue-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600"
          >
            Schedule Strategy Call
            <ArrowRight className="h-4 w-4" />
          </Link>
          <Link
            href="#pricing"
            className="inline-flex items-center gap-2 rounded-full border border-slate-200 px-4 py-2 text-sm font-semibold text-slate-700 transition hover:border-slate-300 hover:bg-slate-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600"
          >
            Review Lifetime Price Lock
          </Link>
        </div>
      </div>
    </div>
  );
}

