/**
 * Allied Advantage - Qualified Lead A/B Variant
 * Generated by GPT-5 Codex on 2025-11-09 to support scarcity-focused landing test.
 */

/**
 * Wireframe & Copy Spec
 * ----------------------------------------------------------------
 * 1. Hero (Full viewport height)
 *    - Headline: "We Only Scale Elite Investors"
 *    - Subhead: Limited capacity positioning; vague criteria hinting at 2+ yrs/20+ deals without specifics.
 *    - Primary CTA button: "See If You Qualify Today" anchor to qualification form.
 *    - Secondary microcopy: "We review 100+ applications monthly. Only 8 seats remain this quarter."
 *
 * 2. Social Proof / Authority Bar
 *    - Horizontal band with quick stats (average ROI uplift, deals per month unlocked, platforms managed).
 *    - Optional logos placeholder using existing brand palette.
 *
 * 3. Qualification Teaser
 *    - Three cards describing "Who Typically Qualifies" using outcomes (consistent deal flow, reinvestment budget, committed operators).
 *    - Include "We decline 72% of applicants" line to reinforce scarcity.
 *
 * 4. Process Snapshot
 *    - 3-step vertical timeline (Apply ➜ Strategy Audit ➜ Launch in 14 days) to communicate speed once accepted.
 *    - Badge showing "Capacity: 8 teams / Quarter" with countdown styling.
 *
 * 5. CTA + Risk Reversal
 *    - Slim section reiterating limited seats, includes bullet assurances (No long-term contract, Dedicated strategist).
 *    - CTA button repeated.
 *
 * 6. FAQ Preview
 *    - 3-4 accordion items seeded inline to address disqualification fears, time to launch, pricing transparency.
 *
 * 7. Qualification Form
 *    - Reuse existing `ConsultationForm` component; relabel surrounding copy to reinforce screening mindset.
 *
 * Tracking & Experiment Notes
 * ----------------------------------------------------------------
 * - Primary conversion: Hero CTA click-through to form (#qualification-form) and Consultation form submission.
 * - Secondary metrics: Scroll depth to Process section, time on page, hero bounce rate.
 * - Variant instrumentation: add data attributes (`data-track`) on CTAs; ensure A/B testing platform logs variant ID `qualify-scarcity-v1`.
 */

import Link from 'next/link'
import ConsultationForm from '@/components/consultation-form'

export const metadata = {
  title: 'Allied Advantage | Limited Partner Program Qualification',
  description:
    'Discover if your wholesaling operation qualifies for Allied Advantage’s AI-powered acquisition system. Limited partner slots and invite-only access.',
}

const authorityHighlights = [
  {
    label: 'Average ROAS Uplift',
    value: '3.4x',
    description: 'after 90 days on platform',
  },
  {
    label: 'Deals Unlocked Monthly',
    value: '12+',
    description: 'per qualified partner',
  },
  {
    label: 'Markets Managed',
    value: '37',
    description: 'multi-channel AI campaigns',
  },
]

const qualificationSignals = [
  {
    title: 'Operators Obsessed with Follow-Through',
    copy: 'You already have acquisition reps or partners ready to run appointments and capitalize on the pipeline we generate.',
  },
  {
    title: 'Deal Velocity Mindset',
    copy: 'You consistently push new opportunities each month and are prepared to reinvest in proven campaigns.',
  },
  {
    title: 'Data-Driven Decision Makers',
    copy: 'You care about tracking, aren’t afraid of dashboards, and will collaborate to iterate campaigns weekly.',
  },
]

const processSteps = [
  {
    step: '01',
    title: 'Apply in 3 Minutes',
    description: 'Share a snapshot of your operation so we can assess fit without revealing proprietary playbooks.',
  },
  {
    step: '02',
    title: 'Strategy Audit',
    description:
      'If prelim qualified, we host a private teardown of your current acquisition funnel and present projections.',
  },
  {
    step: '03',
    title: 'Launch in 14 Days',
    description: 'Accepted partners receive dedicated onboarding, AI campaign deployment, and conversion assets.',
  },
]

const faqs = [
  {
    question: 'What criteria do you use to approve partners?',
    answer:
      'We collaborate with teams who already have momentum. Expect us to look at historical consistency, operational readiness, and your ability to handle additional deal flow.',
  },
  {
    question: 'Do I need a massive ad budget to qualify?',
    answer:
      'No, but you should be prepared to scale quickly once results come in. We help you structure budgets after the strategy audit.',
  },
  {
    question: 'How fast can we launch campaigns after acceptance?',
    answer:
      'Our AI media stack deploys within 14 days of agreement, including landing pages, creative, and conversion tracking.',
  },
  {
    question: 'Is this a long-term contract?',
    answer:
      'We operate on performance-aligned agreements. You stay while we over-deliver. Many partners remain for multiple quarters.',
  },
]

export default function QualifyPage() {
  return (
    <>
      <section className="relative overflow-hidden bg-slate-950 text-white">
        <div className="absolute inset-0 bg-gradient-to-br from-blue-900/80 via-slate-900/90 to-slate-950" />
        <div className="relative mx-auto flex min-h-screen max-w-6xl flex-col px-6 pb-24 pt-32 sm:px-8 md:flex-row md:items-center md:pt-36">
          <div className="w-full max-w-2xl">
            <p className="mb-4 inline-flex items-center rounded-full bg-blue-500/20 px-4 py-1 text-xs font-semibold uppercase tracking-[0.2em] text-blue-200">
              Invite-Only Capacity • 8 Partners per Quarter
            </p>
            <h1 className="text-4xl font-extrabold tracking-tight sm:text-5xl md:text-6xl">
              We Only Scale Elite Investors Ready for Their Next Breakthrough
            </h1>
            <p className="mt-6 text-lg text-slate-200 sm:text-xl">
              Our AI-powered acquisition engine helps top-tier wholesale teams dominate motivated seller demand. We
              review over 100 applications monthly and only advance the operators who prove they can handle the volume.
            </p>
            <div className="mt-8 flex flex-col gap-4 sm:flex-row sm:items-center">
              <Link
                href="#qualification-form"
                data-track="cta-primary"
                className="inline-flex items-center justify-center rounded-full bg-blue-500 px-8 py-4 text-lg font-semibold text-white shadow-lg transition hover:-translate-y-0.5 hover:bg-blue-400 hover:shadow-xl"
              >
                See If You Qualify Today
              </Link>
              <span className="text-sm text-blue-200">
                We maintain a waitlist once capacity is reached. If the button is active, seats remain.
              </span>
            </div>
            <div className="mt-8 flex flex-wrap gap-6 text-sm text-slate-300 md:text-base">
              <div className="flex items-center gap-3">
                <span className="inline-flex h-10 w-10 items-center justify-center rounded-full bg-blue-500/20 text-blue-200">
                  92%
                </span>
                <div>
                  <p className="font-semibold text-white">Acceptance Rate: 8%</p>
                  <p>We decline most applicants to protect campaign performance.</p>
                </div>
              </div>
              <div className="flex items-center gap-3">
                <span className="inline-flex h-10 w-10 items-center justify-center rounded-full bg-blue-500/20 text-blue-200">
                  14
                </span>
                <div>
                  <p className="font-semibold text-white">Days to Deployment</p>
                  <p>Once accepted, your campaigns launch in under two weeks.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="border-b border-slate-200 bg-white">
        <div className="mx-auto max-w-6xl px-6 py-12 sm:px-8">
          <div className="grid gap-6 sm:grid-cols-3">
            {authorityHighlights.map(highlight => (
              <div key={highlight.label} className="rounded-2xl border border-slate-100 bg-slate-50 px-6 py-8 shadow-sm">
                <p className="text-sm font-semibold uppercase tracking-wide text-slate-500">{highlight.label}</p>
                <p className="mt-3 text-3xl font-bold text-slate-900">{highlight.value}</p>
                <p className="mt-2 text-sm text-slate-600">{highlight.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="bg-slate-900 py-20">
        <div className="mx-auto max-w-6xl px-6 sm:px-8">
          <div className="grid gap-12 lg:grid-cols-[1.2fr,1fr] lg:items-center">
            <div>
              <p className="text-sm font-semibold uppercase tracking-[0.2em] text-blue-300">Who Typically Qualifies?</p>
              <h2 className="mt-4 text-3xl font-bold text-white sm:text-4xl">
                We partner with operators who already dominate their backyard and are hungry for more.
              </h2>
              <p className="mt-6 text-lg text-slate-300">
                Every quarter we accept fewer than 10 teams. If you&apos;re still guessing at your metrics or hoping ads
                can fix broken follow-up, we&apos;re not the right fit.
              </p>
              <div className="mt-8 grid gap-6 sm:grid-cols-2">
                {qualificationSignals.map(signal => (
                  <div key={signal.title} className="rounded-2xl border border-blue-500/20 bg-slate-950/60 p-6">
                    <h3 className="text-lg font-semibold text-white">{signal.title}</h3>
                    <p className="mt-3 text-sm text-slate-300">{signal.copy}</p>
                  </div>
                ))}
              </div>
              <p className="mt-8 text-sm text-blue-200">
                We politely decline 72% of applicants. That keeps the pipeline sharp for those already executing.
              </p>
            </div>
            <div className="relative rounded-3xl border border-blue-500/30 bg-gradient-to-br from-blue-700/40 via-slate-900 to-slate-950 p-10 text-white shadow-2xl">
              <div className="absolute -top-6 left-1/2 -translate-x-1/2">
                <span className="rounded-full border border-blue-500 bg-slate-950 px-6 py-2 text-xs font-semibold uppercase tracking-[0.3em] text-blue-200">
                  Limited Capacity
                </span>
              </div>
              <p className="text-sm uppercase tracking-[0.3em] text-blue-200">Seats Remaining This Quarter</p>
              <p className="mt-4 text-6xl font-bold text-white">8</p>
              <p className="mt-2 text-sm text-slate-200">Applications reviewed weekly • invite-only onboarding</p>
              <div className="mt-8 space-y-4 text-sm text-slate-100">
                <p>✔️ AI media buying across Google, Meta, and YouTube</p>
                <p>✔️ Conversion labs building landing assets tailored to your brand</p>
                <p>✔️ Weekly revenue rooms with your strategist</p>
              </div>
              <Link
                href="#qualification-form"
                data-track="cta-secondary"
                className="mt-10 inline-flex w-full items-center justify-center rounded-full bg-blue-500 px-6 py-3 text-base font-semibold text-white shadow-lg transition hover:-translate-y-0.5 hover:bg-blue-400"
              >
                Submit Your Application
              </Link>
              <p className="mt-4 text-xs text-blue-200">
                If the application window is closed, join the waitlist and we&apos;ll notify you the moment a slot opens.
              </p>
            </div>
          </div>
        </div>
      </section>

      <section className="relative bg-white py-20">
        <div className="absolute inset-x-0 top-0 h-24 bg-gradient-to-b from-slate-900/60 to-transparent" aria-hidden />
        <div className="relative mx-auto max-w-6xl px-6 sm:px-8">
          <div className="mx-auto max-w-3xl text-center">
            <p className="text-sm font-semibold uppercase tracking-[0.3em] text-blue-500">Your Fast-Track Timeline</p>
            <h2 className="mt-4 text-3xl font-bold text-slate-900 sm:text-4xl">
              The Application Process Is Deliberate So We Can Scale You Faster
            </h2>
            <p className="mt-6 text-lg text-slate-600">
              No fluff. We simply need to confirm you have the fundamentals dialed in. If you do, we go all-in with you.
            </p>
          </div>
          <div className="mt-12 grid gap-10 md:grid-cols-3">
            {processSteps.map(step => (
              <div key={step.step} className="flex flex-col rounded-3xl border border-slate-100 bg-slate-50 p-8 shadow-sm">
                <span className="text-sm font-semibold uppercase tracking-[0.3em] text-blue-500">{step.step}</span>
                <h3 className="mt-4 text-xl font-semibold text-slate-900">{step.title}</h3>
                <p className="mt-3 text-sm text-slate-600">{step.description}</p>
              </div>
            ))}
          </div>
          <div className="mt-12 rounded-3xl border border-blue-500/30 bg-blue-50 p-8 text-center sm:p-10">
            <h3 className="text-2xl font-bold text-blue-900">No Retainer Risk. Performance Is Earned Monthly.</h3>
            <p className="mt-4 text-base text-blue-900/80">
              If you&apos;re accepted, we give you dedicated launch resources, conversion assets, and live call tracking from
              day one. We stay laser-focused on your cost per deal.
            </p>
            <Link
              href="#qualification-form"
              data-track="cta-tertiary"
              className="mt-8 inline-flex items-center justify-center rounded-full bg-blue-600 px-10 py-4 text-lg font-semibold text-white shadow-lg transition hover:-translate-y-0.5 hover:bg-blue-500"
            >
              Lock In Your Spot
            </Link>
            <p className="mt-3 text-xs text-blue-700">
              If you&apos;re unsure whether you&apos;re a fit, apply anyway. We&apos;ll audit and let you know in 48 hours.
            </p>
          </div>
        </div>
      </section>

      <section className="bg-slate-950 py-20 text-white">
        <div className="mx-auto max-w-5xl px-6 sm:px-8">
          <div className="grid gap-10 md:grid-cols-2">
            <div>
              <h2 className="text-3xl font-bold sm:text-4xl">Questions from Operators Like You</h2>
              <p className="mt-4 text-base text-slate-300">
                We keep the publicly-facing details selective. Bring your full scenario to the application and we&apos;ll give
                custom answers on the call.
              </p>
            </div>
            <div className="space-y-6">
              {faqs.map(item => (
                <div key={item.question} className="rounded-2xl border border-blue-500/20 bg-slate-900/70 p-6">
                  <h3 className="text-lg font-semibold text-white">{item.question}</h3>
                  <p className="mt-3 text-sm text-slate-300">{item.answer}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      <section id="qualification-form" className="relative overflow-hidden bg-gradient-to-br from-slate-900 via-slate-950 to-slate-900 py-24">
        <div className="absolute inset-0 opacity-40">
          <div className="h-full w-full" style={{ backgroundImage: 'radial-gradient(circle at 20% 20%, rgba(59,130,246,0.25), transparent 55%)' }} />
        </div>
        <div className="relative mx-auto max-w-5xl px-6 sm:px-8">
          <div className="mx-auto max-w-2xl text-center text-white">
            <p className="text-sm font-semibold uppercase tracking-[0.3em] text-blue-300">Final Step</p>
            <h2 className="mt-4 text-3xl font-bold sm:text-4xl">Tell Us Why You&apos;re Ready for an Elite Partnership</h2>
            <p className="mt-4 text-lg text-slate-200">
              Share a concise picture of your operation. We review every application manually and respond within two
              business days.
            </p>
          </div>
          <div className="mt-12 rounded-3xl border border-blue-500/20 bg-slate-950/90 p-6 shadow-2xl sm:p-10">
            <ConsultationForm />
          </div>
          <p className="mt-6 text-center text-xs text-blue-200">
            We never resell your data. Your submission triggers a confidential review by the Allied Advantage leadership
            team.
          </p>
        </div>
      </section>
    </>
  )
}

/**
 * Tracking Implementation Outline
 * ----------------------------------------------------------------
 * - Add analytics integration (e.g., Segment or Vercel Analytics) to record:
 *   • data-track=cta-primary/secondary/tertiary click events with variantId=qualify-scarcity-v1.
 *   • Form submission success/failure from ConsultationForm (extend component to emit custom events).
 *   • Scroll depth 25/50/75/100 to attribute engagement.
 * - Configure A/B testing platform to split traffic between `/` (control) and `/qualify` (variant).
 * - Monitor KPIs: CTA CTR, qualified application rate, average time on page, bounce rate, downstream booked calls.
 */

